//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singleton.WebApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HgsWebServiceSoap")]
    public interface HgsWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name isim from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgsEkle", ReplyAction="*")]
        Singleton.WebApp.ServiceReference1.hgsEkleResponse hgsEkle(Singleton.WebApp.ServiceReference1.hgsEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgsEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsEkleResponse> hgsEkleAsync(Singleton.WebApp.ServiceReference1.hgsEkleRequest request);
        
        // CODEGEN: Generating message contract since element name hgsSorgulaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgsSorgula", ReplyAction="*")]
        Singleton.WebApp.ServiceReference1.hgsSorgulaResponse hgsSorgula(Singleton.WebApp.ServiceReference1.hgsSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgsSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsSorgulaResponse> hgsSorgulaAsync(Singleton.WebApp.ServiceReference1.hgsSorgulaRequest request);
        
        // CODEGEN: Generating message contract since element name hgsSatisResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgsSatis", ReplyAction="*")]
        Singleton.WebApp.ServiceReference1.hgsSatisResponse hgsSatis(Singleton.WebApp.ServiceReference1.hgsSatisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hgsSatis", ReplyAction="*")]
        System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsSatisResponse> hgsSatisAsync(Singleton.WebApp.ServiceReference1.hgsSatisRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hgsEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hgsEkle", Namespace="http://tempuri.org/", Order=0)]
        public Singleton.WebApp.ServiceReference1.hgsEkleRequestBody Body;
        
        public hgsEkleRequest() {
        }
        
        public hgsEkleRequest(Singleton.WebApp.ServiceReference1.hgsEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hgsEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long hgsNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long tc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string isim;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string soyisim;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string plaka;
        
        public hgsEkleRequestBody() {
        }
        
        public hgsEkleRequestBody(long hgsNo, long tc, string isim, string soyisim, string plaka) {
            this.hgsNo = hgsNo;
            this.tc = tc;
            this.isim = isim;
            this.soyisim = soyisim;
            this.plaka = plaka;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hgsEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hgsEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Singleton.WebApp.ServiceReference1.hgsEkleResponseBody Body;
        
        public hgsEkleResponse() {
        }
        
        public hgsEkleResponse(Singleton.WebApp.ServiceReference1.hgsEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hgsEkleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool hgsEkleResult;
        
        public hgsEkleResponseBody() {
        }
        
        public hgsEkleResponseBody(bool hgsEkleResult) {
            this.hgsEkleResult = hgsEkleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hgsSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hgsSorgula", Namespace="http://tempuri.org/", Order=0)]
        public Singleton.WebApp.ServiceReference1.hgsSorgulaRequestBody Body;
        
        public hgsSorgulaRequest() {
        }
        
        public hgsSorgulaRequest(Singleton.WebApp.ServiceReference1.hgsSorgulaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hgsSorgulaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int HgsID;
        
        public hgsSorgulaRequestBody() {
        }
        
        public hgsSorgulaRequestBody(int HgsID) {
            this.HgsID = HgsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hgsSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hgsSorgulaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Singleton.WebApp.ServiceReference1.hgsSorgulaResponseBody Body;
        
        public hgsSorgulaResponse() {
        }
        
        public hgsSorgulaResponse(Singleton.WebApp.ServiceReference1.hgsSorgulaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hgsSorgulaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hgsSorgulaResult;
        
        public hgsSorgulaResponseBody() {
        }
        
        public hgsSorgulaResponseBody(string hgsSorgulaResult) {
            this.hgsSorgulaResult = hgsSorgulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hgsSatisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hgsSatis", Namespace="http://tempuri.org/", Order=0)]
        public Singleton.WebApp.ServiceReference1.hgsSatisRequestBody Body;
        
        public hgsSatisRequest() {
        }
        
        public hgsSatisRequest(Singleton.WebApp.ServiceReference1.hgsSatisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hgsSatisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal hgsBakiye;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int HgsID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal tutar;
        
        public hgsSatisRequestBody() {
        }
        
        public hgsSatisRequestBody(decimal hgsBakiye, int HgsID, decimal tutar) {
            this.hgsBakiye = hgsBakiye;
            this.HgsID = HgsID;
            this.tutar = tutar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hgsSatisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hgsSatisResponse", Namespace="http://tempuri.org/", Order=0)]
        public Singleton.WebApp.ServiceReference1.hgsSatisResponseBody Body;
        
        public hgsSatisResponse() {
        }
        
        public hgsSatisResponse(Singleton.WebApp.ServiceReference1.hgsSatisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hgsSatisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hgsSatisResult;
        
        public hgsSatisResponseBody() {
        }
        
        public hgsSatisResponseBody(string hgsSatisResult) {
            this.hgsSatisResult = hgsSatisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HgsWebServiceSoapChannel : Singleton.WebApp.ServiceReference1.HgsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HgsWebServiceSoapClient : System.ServiceModel.ClientBase<Singleton.WebApp.ServiceReference1.HgsWebServiceSoap>, Singleton.WebApp.ServiceReference1.HgsWebServiceSoap {
        
        public HgsWebServiceSoapClient() {
        }
        
        public HgsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HgsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HgsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HgsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Singleton.WebApp.ServiceReference1.hgsEkleResponse Singleton.WebApp.ServiceReference1.HgsWebServiceSoap.hgsEkle(Singleton.WebApp.ServiceReference1.hgsEkleRequest request) {
            return base.Channel.hgsEkle(request);
        }
        
        public bool hgsEkle(long hgsNo, long tc, string isim, string soyisim, string plaka) {
            Singleton.WebApp.ServiceReference1.hgsEkleRequest inValue = new Singleton.WebApp.ServiceReference1.hgsEkleRequest();
            inValue.Body = new Singleton.WebApp.ServiceReference1.hgsEkleRequestBody();
            inValue.Body.hgsNo = hgsNo;
            inValue.Body.tc = tc;
            inValue.Body.isim = isim;
            inValue.Body.soyisim = soyisim;
            inValue.Body.plaka = plaka;
            Singleton.WebApp.ServiceReference1.hgsEkleResponse retVal = ((Singleton.WebApp.ServiceReference1.HgsWebServiceSoap)(this)).hgsEkle(inValue);
            return retVal.Body.hgsEkleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsEkleResponse> Singleton.WebApp.ServiceReference1.HgsWebServiceSoap.hgsEkleAsync(Singleton.WebApp.ServiceReference1.hgsEkleRequest request) {
            return base.Channel.hgsEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsEkleResponse> hgsEkleAsync(long hgsNo, long tc, string isim, string soyisim, string plaka) {
            Singleton.WebApp.ServiceReference1.hgsEkleRequest inValue = new Singleton.WebApp.ServiceReference1.hgsEkleRequest();
            inValue.Body = new Singleton.WebApp.ServiceReference1.hgsEkleRequestBody();
            inValue.Body.hgsNo = hgsNo;
            inValue.Body.tc = tc;
            inValue.Body.isim = isim;
            inValue.Body.soyisim = soyisim;
            inValue.Body.plaka = plaka;
            return ((Singleton.WebApp.ServiceReference1.HgsWebServiceSoap)(this)).hgsEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Singleton.WebApp.ServiceReference1.hgsSorgulaResponse Singleton.WebApp.ServiceReference1.HgsWebServiceSoap.hgsSorgula(Singleton.WebApp.ServiceReference1.hgsSorgulaRequest request) {
            return base.Channel.hgsSorgula(request);
        }
        
        public string hgsSorgula(int HgsID) {
            Singleton.WebApp.ServiceReference1.hgsSorgulaRequest inValue = new Singleton.WebApp.ServiceReference1.hgsSorgulaRequest();
            inValue.Body = new Singleton.WebApp.ServiceReference1.hgsSorgulaRequestBody();
            inValue.Body.HgsID = HgsID;
            Singleton.WebApp.ServiceReference1.hgsSorgulaResponse retVal = ((Singleton.WebApp.ServiceReference1.HgsWebServiceSoap)(this)).hgsSorgula(inValue);
            return retVal.Body.hgsSorgulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsSorgulaResponse> Singleton.WebApp.ServiceReference1.HgsWebServiceSoap.hgsSorgulaAsync(Singleton.WebApp.ServiceReference1.hgsSorgulaRequest request) {
            return base.Channel.hgsSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsSorgulaResponse> hgsSorgulaAsync(int HgsID) {
            Singleton.WebApp.ServiceReference1.hgsSorgulaRequest inValue = new Singleton.WebApp.ServiceReference1.hgsSorgulaRequest();
            inValue.Body = new Singleton.WebApp.ServiceReference1.hgsSorgulaRequestBody();
            inValue.Body.HgsID = HgsID;
            return ((Singleton.WebApp.ServiceReference1.HgsWebServiceSoap)(this)).hgsSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Singleton.WebApp.ServiceReference1.hgsSatisResponse Singleton.WebApp.ServiceReference1.HgsWebServiceSoap.hgsSatis(Singleton.WebApp.ServiceReference1.hgsSatisRequest request) {
            return base.Channel.hgsSatis(request);
        }
        
        public string hgsSatis(decimal hgsBakiye, int HgsID, decimal tutar) {
            Singleton.WebApp.ServiceReference1.hgsSatisRequest inValue = new Singleton.WebApp.ServiceReference1.hgsSatisRequest();
            inValue.Body = new Singleton.WebApp.ServiceReference1.hgsSatisRequestBody();
            inValue.Body.hgsBakiye = hgsBakiye;
            inValue.Body.HgsID = HgsID;
            inValue.Body.tutar = tutar;
            Singleton.WebApp.ServiceReference1.hgsSatisResponse retVal = ((Singleton.WebApp.ServiceReference1.HgsWebServiceSoap)(this)).hgsSatis(inValue);
            return retVal.Body.hgsSatisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsSatisResponse> Singleton.WebApp.ServiceReference1.HgsWebServiceSoap.hgsSatisAsync(Singleton.WebApp.ServiceReference1.hgsSatisRequest request) {
            return base.Channel.hgsSatisAsync(request);
        }
        
        public System.Threading.Tasks.Task<Singleton.WebApp.ServiceReference1.hgsSatisResponse> hgsSatisAsync(decimal hgsBakiye, int HgsID, decimal tutar) {
            Singleton.WebApp.ServiceReference1.hgsSatisRequest inValue = new Singleton.WebApp.ServiceReference1.hgsSatisRequest();
            inValue.Body = new Singleton.WebApp.ServiceReference1.hgsSatisRequestBody();
            inValue.Body.hgsBakiye = hgsBakiye;
            inValue.Body.HgsID = HgsID;
            inValue.Body.tutar = tutar;
            return ((Singleton.WebApp.ServiceReference1.HgsWebServiceSoap)(this)).hgsSatisAsync(inValue);
        }
    }
}
